# Image Python légère
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY handler.py ./

ENV fprocess="python handler.py"
EXPOSE 8080
CMD ["fwatchdog"]