apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: openfaas
type: Opaque
data:
  POSTGRES_HOST: cG9zdGdyZXM=        # "postgres"
  POSTGRES_DB: b3BlbmZhYXM=          # "openfaas"
  POSTGRES_USER: dXNlcg==            # "user"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=    # "password"
  POSTGRES_PORT: NTQzMg==            # "5432"